import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js";
import { getDatabase, ref, get, onValue, update } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-database.js";
import { firebaseConfig } from "./firebase-config.js";

const SESSION_KEY='preorder_admin_session', SESSION_DAYS=7;
const app=initializeApp(firebaseConfig), db=getDatabase(app), $=id=>document.getElementById(id);
const loginScreen=$('loginScreen'), adminApp=$('adminApp'), loginForm=$('loginForm'), username=$('username'), password=$('password'), remember=$('remember'), loginBtn=$('loginBtn'), loginText=$('loginText'), loginLoader=$('loginLoader'), adminUser=$('adminUser');
const dashboard=$('dashboard'), ordersView=$('orders'), title=$('title'), nav=[...document.querySelectorAll('.nav')];
const tbody=$('tbody'), recent=$('recent'), recentEmpty=$('recentEmpty'), emptyOrders=$('emptyOrders'), search=$('search'), statusFilter=$('statusFilter'), levelFilter=$('levelFilter');
const detail=$('detail'), dRef=$('dRef'), dStudent=$('dStudent'), dName=$('dName'), dClass=$('dClass'), dPhone=$('dPhone'), dContact=$('dContact'), dQty=$('dQty'), dUnit=$('dUnit'), dTotal=$('dTotal'), dDate=$('dDate'), dSlip=$('dSlip'), openSlip=$('openSlip');
let data=[], selectedId=null, unsub=null, currentAdmin=null;
restore();

loginForm.addEventListener('submit',async e=>{e.preventDefault();const user=normalize(username.value),pass=password.value;if(!user||!pass){toast('กรุณากรอกชื่อผู้ใช้และรหัสผ่าน','error');return}setLogin(true);try{const snap=await get(ref(db,`adminAccounts/${user}`));if(!snap.exists())throw 0;const acc=snap.val(),hash=await sha256(pass);if(!acc.passwordHash||!same(hash.toLowerCase(),String(acc.passwordHash).toLowerCase()))throw 0;currentAdmin={username:user,role:acc.role||'admin'};saveSession(currentAdmin,remember.checked);password.value='';showAdmin();subscribe()}catch(err){console.error(err);toast('ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง','error')}finally{setLogin(false)}});
$('logout').addEventListener('click',()=>{clearSession();hideAdmin()});
function saveSession(admin,keep){const v=JSON.stringify({...admin,expiresAt:Date.now()+(keep?SESSION_DAYS*86400000:12*3600000)});(keep?localStorage:sessionStorage).setItem(SESSION_KEY,v);(keep?sessionStorage:localStorage).removeItem(SESSION_KEY)}
function restore(){const raw=localStorage.getItem(SESSION_KEY)||sessionStorage.getItem(SESSION_KEY);if(!raw){hideAdmin();return}try{const s=JSON.parse(raw);if(!s.expiresAt||Date.now()>=s.expiresAt){clearSession();hideAdmin();return}currentAdmin={username:s.username,role:s.role||'admin'};showAdmin();subscribe()}catch{clearSession();hideAdmin()}}
function clearSession(){localStorage.removeItem(SESSION_KEY);sessionStorage.removeItem(SESSION_KEY);currentAdmin=null;if(unsub){unsub();unsub=null}}
function showAdmin(){loginScreen.classList.add('hidden');adminApp.classList.remove('hidden');adminUser.textContent=currentAdmin?.username||'Admin'}
function hideAdmin(){adminApp.classList.add('hidden');loginScreen.classList.remove('hidden')}

nav.forEach(b=>b.addEventListener('click',()=>openView(b.dataset.view)));$('showAll').addEventListener('click',()=>openView('orders'));function openView(v){nav.forEach(b=>b.classList.toggle('active',b.dataset.view===v));const d=v==='dashboard';dashboard.classList.toggle('active',d);ordersView.classList.toggle('active',!d);title.textContent=d?'ภาพรวมพรีออเดอร์':'คำสั่งซื้อทั้งหมด'}
function subscribe(){if(unsub)unsub();unsub=onValue(ref(db,'preorders'),snap=>{const raw=snap.val()||{};data=Object.entries(raw).map(([id,v])=>({id,...v})).sort((a,b)=>ts(b)-ts(a));renderAll()},err=>{console.error(err);toast('โหลดข้อมูลไม่สำเร็จ','error')})}
function renderAll(){renderStats();renderRecent();renderTable()}
function renderStats(){const today=dateKey(new Date());$('totalOrders').textContent=data.length;$('totalBags').textContent=data.reduce((s,x)=>s+Number(x?.order?.quantity||0),0).toLocaleString('th-TH');$('totalRevenue').textContent=money(data.reduce((s,x)=>s+Number(x?.order?.totalAmount||0),0));$('pendingCount').textContent=data.filter(x=>status(x)==='pending').length;$('verifiedCount').textContent=data.filter(x=>status(x)==='verified').length;$('todayCount').textContent=data.filter(x=>{const d=toDate(x.createdAt);return d&&dateKey(d)===today}).length}
function renderRecent(){recent.innerHTML='';const list=data.slice(0,6);recentEmpty.classList.toggle('hidden',list.length>0);list.forEach(o=>{const row=document.createElement('div');row.className='recent-row';row.innerHTML=`<div><strong>${esc(name(o))}</strong><span>${esc(o.referenceCode||'-')} · ${esc(o?.customer?.studentId||'-')}</span></div><div><span>จำนวน</span><strong>${Number(o?.order?.quantity||0)} ใบ</strong></div><div><span>ยอด</span><strong>${money(o?.order?.totalAmount||0)}</strong></div><div><span>สถานะ</span>${badge(o)}</div><button class="small-btn" data-detail="${o.id}">รายละเอียด</button>`;recent.appendChild(row)});attach()}
function renderTable(){const q=search.value.trim().toLowerCase(),st=statusFilter.value,lv=levelFilter.value;const list=data.filter(o=>{const c=o.customer||{};if(st&&status(o)!==st)return false;if(lv&&c.level!==lv)return false;if(!q)return true;return [o.referenceCode,name(o),c.studentId,c.phone,c.level,c.room,c?.contact?.value].filter(Boolean).join(' ').toLowerCase().includes(q)});tbody.innerHTML='';emptyOrders.classList.toggle('hidden',list.length>0);list.forEach(o=>{const c=o.customer||{},d=toDate(o.createdAt),tr=document.createElement('tr');tr.innerHTML=`<td><strong>${esc(name(o))}</strong><br><small>${esc(o.referenceCode||'-')} · ${esc(c.studentId||'-')}</small></td><td>${esc(c.level||'-')} / ${esc(c.room||'-')}</td><td>${Number(o?.order?.quantity||0)} ใบ</td><td><strong>${money(o?.order?.totalAmount||0)}</strong></td><td>${badge(o)}</td><td>${d?esc(formatDate(d)):'-'}</td><td><button class="small-btn" data-detail="${o.id}">ดูรายละเอียด</button></td>`;tbody.appendChild(tr)});attach()}
search.addEventListener('input',renderTable);statusFilter.addEventListener('change',renderTable);levelFilter.addEventListener('change',renderTable);$('refresh').addEventListener('click',()=>{renderAll();toast('รีเฟรชข้อมูลแล้ว','success')});
function attach(){document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>openDetail(b.dataset.detail))}
function openDetail(id){const o=data.find(x=>x.id===id);if(!o)return;selectedId=id;const c=o.customer||{},od=o.order||{},p=o.payment||{},d=toDate(o.createdAt);dRef.textContent=o.referenceCode||'-';dStudent.textContent=c.studentId||'-';dName.textContent=name(o);dClass.textContent=`${c.level||'-'} / ห้อง ${c.room||'-'}`;dPhone.textContent=c.phone||'-';dContact.textContent=`${c?.contact?.type==='instagram'?'Instagram':'Facebook'} · ${c?.contact?.value||'-'}`;dQty.textContent=`${Number(od.quantity||0)} ใบ`;dUnit.textContent=money(od.unitPrice||0);dTotal.textContent=money(od.totalAmount||0);dDate.textContent=d?formatDate(d):'-';dSlip.src=p.slipData||'';openSlip.href=p.slipData||'#';detail.classList.remove('hidden')}
document.querySelectorAll('[data-close]').forEach(x=>x.addEventListener('click',()=>detail.classList.add('hidden')));
document.querySelectorAll('[data-status]').forEach(b=>b.addEventListener('click',async()=>{if(!selectedId)return;const st=b.dataset.status;b.disabled=true;try{await update(ref(db,`preorders/${selectedId}`),{'payment/status':st,status:st==='verified'?'payment_verified':st==='rejected'?'payment_issue':'pending_review',reviewedAt:Date.now(),reviewedBy:currentAdmin?.username||'admin'});toast('อัปเดตสถานะแล้ว','success');detail.classList.add('hidden')}catch(err){console.error(err);toast('อัปเดตสถานะไม่สำเร็จ','error')}finally{b.disabled=false}}));

const status=o=>o?.payment?.status||'pending';function badge(o){const s=status(o),labels={pending:'รอตรวจสอบ',verified:'ยืนยันแล้ว',rejected:'มีปัญหา'};return`<span class="status ${s}">${labels[s]||'รอตรวจสอบ'}</span>`}function name(o){const c=o.customer||{};return`${c.prefix||''}${c.firstName||''} ${c.lastName||''}`.trim()}function normalize(v){return String(v||'').trim().toLowerCase().replace(/[.#$\[\]\/]/g,'')}async function sha256(t){const b=new TextEncoder().encode(t),h=await crypto.subtle.digest('SHA-256',b);return Array.from(new Uint8Array(h)).map(x=>x.toString(16).padStart(2,'0')).join('')}function same(a,b){if(a.length!==b.length)return false;let r=0;for(let i=0;i<a.length;i++)r|=a.charCodeAt(i)^b.charCodeAt(i);return r===0}function setLogin(x){loginBtn.disabled=x;loginText.classList.toggle('hidden',x);loginLoader.classList.toggle('hidden',!x)}function ts(o){const d=toDate(o?.createdAt);return d?d.getTime():0}function toDate(v){return typeof v==='number'?new Date(v):null}function dateKey(d){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}function formatDate(d){return new Intl.DateTimeFormat('th-TH',{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(d)}const money=v=>`฿${Number(v||0).toLocaleString('th-TH')}`;function esc(v=''){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}function toast(m,t=''){const box=$('toast'),e=document.createElement('div');e.className=`toast ${t}`;e.textContent=m;box.appendChild(e);setTimeout(()=>e.remove(),4000)}
